# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: doit
    binary: doit
    main: ./cmd/todo/
    env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - illumos
      - solaris
      - js
    
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - mips
      - mipsle
      - mips64
      - mips64le
      - riscv64
      - s390x
      - ppc64le
      - wasm

    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64
      - goos: js
        goarch: amd64
      - goos: js
        goarch: arm64
      - goos: js
        goarch: "386"
    
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      doit_
      {{- title .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: aakku106
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://adarashagaihre.com.np"
    description: "A sleek CLI Task manager tool built with Go & WASM SQLite3."
    install: |
      bin.install "doit"

release:
  footer: >-

    ---
    
    ### Contact & Links
    
    * **Built by:** [@aakku106](https://github.com/aakku106)
    
    * **Website:** [adarashagaihre.com.np](https://adarashagaihre.com.np)
    
    * **Support Email:** aakku@adarashagaihre.com.np | adarasha.gaihre106@gmail.com
