// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package try2

import (
	"context"
)

const createCat = `-- name: CreateCat :one
insert into cat(
name,desc
) values (
  ?,?
  )
RETURNING id, name, "desc"
`

type CreateCatParams struct {
	Name any
	Desc any
}

func (q *Queries) CreateCat(ctx context.Context, arg CreateCatParams) (Cat, error) {
	row := q.db.QueryRowContext(ctx, createCat, arg.Name, arg.Desc)
	var i Cat
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}
