// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type Completed struct {
	ID          int64     `json:"id"`
	Session     string    `json:"session"`
	Title       string    `json:"title"`
	CompletedAt time.Time `json:"completed_at"`
}

type Ignored struct {
	ID        int64     `json:"id"`
	Session   string    `json:"session"`
	Title     string    `json:"title"`
	ExpiredAt time.Time `json:"expired_at"`
}

type Todo struct {
	ID        int64        `json:"id"`
	Session   string       `json:"session"`
	Title     string       `json:"title"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type Trash struct {
	ID        int64     `json:"id"`
	Session   string    `json:"session"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	RemovedAt time.Time `json:"removed_at"`
}
