// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID        int64        `json:"id"`
	Session   string       `json:"session"`
	Title     string       `json:"title"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	Completed int64        `json:"completed"`
}
