// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (
    session,
    title,
    expires_at
) VALUES (?, ?, ?)
`

type CreateTodoParams struct {
	Session   string       `json:"session"`
	Title     string       `json:"title"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo, arg.Session, arg.Title, arg.ExpiresAt)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const listTodos = `-- name: ListTodos :many
SELECT id, session, title, created_at, expires_at, completed FROM todos
WHERE session = ?
ORDER BY created_at
`

func (q *Queries) ListTodos(ctx context.Context, session string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.Title,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
