// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const completeTodoTransaction = `-- name: CompleteTodoTransaction :exec
INSERT INTO completed (session, title)
SELECT t.session, t.title FROM todos AS t
WHERE t.id = ?
`

func (q *Queries) CompleteTodoTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTodoTransaction, id)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, session, expires_at)
VALUES (?, ?, ?)
RETURNING id, session, title, created_at, expires_at
`

type CreateTodoParams struct {
	Title     string       `json:"title"`
	Session   string       `json:"session"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Session, arg.ExpiresAt)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteFromTodos = `-- name: DeleteFromTodos :exec
DELETE FROM todos 
WHERE todos.id = ?
`

func (q *Queries) DeleteFromTodos(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFromTodos, id)
	return err
}

const listTodoIDs = `-- name: ListTodoIDs :many
SELECT t.id FROM todos AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

func (q *Queries) ListTodoIDs(ctx context.Context, session string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTodoIDs, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT t.id, t.title FROM todos AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

type ListTodosRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListTodos(ctx context.Context, session string) ([]ListTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodosRow
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashTodoTransaction = `-- name: TrashTodoTransaction :exec
INSERT INTO trash (session, title, created_at)
SELECT t.session, t.title, t.created_at FROM todos AS t
WHERE t.id = ?
`

func (q *Queries) TrashTodoTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, trashTodoTransaction, id)
	return err
}
