// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const clearCompleted = `-- name: ClearCompleted :exec
DELETE FROM completed
`

func (q *Queries) ClearCompleted(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCompleted)
	return err
}

const clearIgnored = `-- name: ClearIgnored :exec
DELETE FROM ignored
`

func (q *Queries) ClearIgnored(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearIgnored)
	return err
}

const clearTrash = `-- name: ClearTrash :exec
DELETE FROM trash
`

func (q *Queries) ClearTrash(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTrash)
	return err
}

const completeTodoTransaction = `-- name: CompleteTodoTransaction :exec
INSERT INTO completed (session, title)
SELECT t.session, t.title FROM todos AS t
WHERE t.id = ?
`

func (q *Queries) CompleteTodoTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTodoTransaction, id)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, session, expires_at)
VALUES (?, ?, ?)
RETURNING id, session, title, created_at, expires_at
`

type CreateTodoParams struct {
	Title     string       `json:"title"`
	Session   string       `json:"session"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Session, arg.ExpiresAt)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteFromCompleted = `-- name: DeleteFromCompleted :exec
DELETE FROM completed
WHERE completed.id = ?
`

func (q *Queries) DeleteFromCompleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFromCompleted, id)
	return err
}

const deleteFromIgnored = `-- name: DeleteFromIgnored :exec
DELETE FROM ignored
WHERE ignored.id = ?
`

func (q *Queries) DeleteFromIgnored(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFromIgnored, id)
	return err
}

const deleteFromTodos = `-- name: DeleteFromTodos :exec
DELETE FROM todos 
WHERE todos.id = ?
`

func (q *Queries) DeleteFromTodos(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFromTodos, id)
	return err
}

const deleteFromTrash = `-- name: DeleteFromTrash :exec
DELETE FROM trash
WHERE trash.id = ?
`

func (q *Queries) DeleteFromTrash(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFromTrash, id)
	return err
}

const listCompleted = `-- name: ListCompleted :many
SELECT c.id, c.title FROM completed AS c
WHERE c.session = ?
ORDER BY c.completed_at DESC
`

type ListCompletedRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListCompleted(ctx context.Context, session string) ([]ListCompletedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleted, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedRow
	for rows.Next() {
		var i ListCompletedRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedIDs = `-- name: ListCompletedIDs :many
SELECT c.id FROM completed AS c
WHERE c.session = ?
ORDER BY c.completed_at DESC
`

func (q *Queries) ListCompletedIDs(ctx context.Context, session string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedIDs, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnored = `-- name: ListIgnored :many
SELECT i.id, i.title FROM ignored AS i
WHERE i.session = ?
ORDER BY i.expired_at DESC
`

type ListIgnoredRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListIgnored(ctx context.Context, session string) ([]ListIgnoredRow, error) {
	rows, err := q.db.QueryContext(ctx, listIgnored, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIgnoredRow
	for rows.Next() {
		var i ListIgnoredRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnoredIDs = `-- name: ListIgnoredIDs :many
SELECT i.id FROM ignored AS i
WHERE i.session = ?
ORDER BY i.expired_at DESC
`

func (q *Queries) ListIgnoredIDs(ctx context.Context, session string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listIgnoredIDs, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoIDs = `-- name: ListTodoIDs :many
SELECT t.id FROM todos AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

func (q *Queries) ListTodoIDs(ctx context.Context, session string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTodoIDs, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT t.id, t.title FROM todos AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

type ListTodosRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListTodos(ctx context.Context, session string) ([]ListTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodosRow
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrash = `-- name: ListTrash :many
SELECT t.id, t.title FROM trash AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

type ListTrashRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) ListTrash(ctx context.Context, session string) ([]ListTrashRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrash, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashRow
	for rows.Next() {
		var i ListTrashRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashIDs = `-- name: ListTrashIDs :many
SELECT t.id FROM trash AS t
WHERE t.session = ?
ORDER BY t.created_at DESC
`

func (q *Queries) ListTrashIDs(ctx context.Context, session string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTrashIDs, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCompletedTo = `-- name: MoveCompletedTo :exec
INSERT INTO todos (session,title)
SELECT c.session, c.title FROM completed AS c
WHERE c.id = ?
`

func (q *Queries) MoveCompletedTo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveCompletedTo, id)
	return err
}

const moveCompletedToIgnored = `-- name: MoveCompletedToIgnored :exec
INSERT INTO ignored (session,title)
SELECT c.session, c.title FROM completed AS c
WHERE c.id = ?
`

func (q *Queries) MoveCompletedToIgnored(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveCompletedToIgnored, id)
	return err
}

const moveCompletedToTrash = `-- name: MoveCompletedToTrash :exec
INSERT INTO trash (session,title,created_at)
SELECT c.session, c.title, c.completed_at FROM completed AS c
WHERE c.id = ?
`

func (q *Queries) MoveCompletedToTrash(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveCompletedToTrash, id)
	return err
}

const moveIgnoredTo = `-- name: MoveIgnoredTo :exec
INSERT INTO todos (session,title)
SELECT i.session, i.title FROM ignored AS i
WHERE i.id = ?
`

func (q *Queries) MoveIgnoredTo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveIgnoredTo, id)
	return err
}

const moveIgnoredToCompleted = `-- name: MoveIgnoredToCompleted :exec
INSERT INTO completed (session,title)
SELECT i.session, i.title FROM ignored AS i
WHERE i.id = ?
`

func (q *Queries) MoveIgnoredToCompleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveIgnoredToCompleted, id)
	return err
}

const moveIgnoredToTrash = `-- name: MoveIgnoredToTrash :exec
INSERT INTO trash (session,title,created_at)
SELECT i.session, i.title, i.expired_at FROM ignored AS i
WHERE i.id = ?
`

func (q *Queries) MoveIgnoredToTrash(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveIgnoredToTrash, id)
	return err
}

const moveTrashTo = `-- name: MoveTrashTo :exec
INSERT INTO todos (session,title)
SELECT t.session, t.title FROM trash AS t
WHERE t.id = ?
`

func (q *Queries) MoveTrashTo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveTrashTo, id)
	return err
}

const moveTrashToCompleted = `-- name: MoveTrashToCompleted :exec
INSERT INTO completed (session,title)
SELECT t.session, t.title FROM trash AS t
WHERE t.id = ?
`

func (q *Queries) MoveTrashToCompleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveTrashToCompleted, id)
	return err
}

const moveTrashToIgnored = `-- name: MoveTrashToIgnored :exec
INSERT INTO completed (session,title)
SELECT t.session, t.title FROM trash AS t
WHERE t.id = ?
`

func (q *Queries) MoveTrashToIgnored(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, moveTrashToIgnored, id)
	return err
}

const trashTodoTransaction = `-- name: TrashTodoTransaction :exec
INSERT INTO trash (session, title, created_at)
SELECT t.session, t.title, t.created_at FROM todos AS t
WHERE t.id = ?
`

func (q *Queries) TrashTodoTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, trashTodoTransaction, id)
	return err
}
