// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CompleteTodoTransaction(ctx context.Context, id int64) error
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteFromTodos(ctx context.Context, id int64) error
	ListTodoIDs(ctx context.Context, session string) ([]int64, error)
	ListTodos(ctx context.Context, session string) ([]ListTodosRow, error)
	TrashTodoTransaction(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
