CREATE TABLE IF NOT EXISTS todos (
    id INTEGER PRIMARY KEY,
    session TEXT NOT NULL DEFAULT 'todo',
    title TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME
);

CREATE TABLE IF NOT EXISTS completed (
    id INTEGER PRIMARY KEY,
    session TEXT NOT NULL DEFAULT 'todo',
    title TEXT NOT NULL,
    completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ignored (
    id INTEGER PRIMARY KEY,
    session TEXT NOT NULL DEFAULT 'todo',
    title TEXT NOT NULL,
    expired_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trash (
    id INTEGER PRIMARY KEY,
    session TEXT NOT NULL DEFAULT 'todo',
    title TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    removed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
