CREATE TABLE IF NOT EXISTS todos (
    id INTEGER PRIMARY KEY,
    session TEXT NOT NULL DEFAULT 'todo',
    title TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME,
    completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0,1))
);
